;%define DEBUG
;%define DEBUG_2
;%define PAGING_ON

MAX_PROCESSES		EQU	16
PROCESS_STRUCT_SIZE	EQU	0FFh

LOWEST_MAJOR_VERSION	EQU	1
LOWEST_MINOR_VERSION	EQU	0

OS_STACK		EQU	90000h

MOUSE_LEFT_CLICK	EQU	1
MOUSE_RIGHT_CLICK	EQU	2
MOUSE_MIDDLE_CLICK	EQU	3

VGA_WIDTH		EQU	800
VGA_HEIGHT		EQU	600
VGA_MODE		EQU	114h	;111 for 640x480x 16 bits
FONT_WIDTH		EQU	8
FONT_HEIGHT		EQU	13

MAX_WINDOWS		EQU	255
WINDOWS_ARRAY_STRUCT_SIZE EQU	128

FIRST_LINE		EQU	23 + 43
FIRST_POS		EQU	6
COLOR_BLACK		EQU	0
COLOR_WHITE		EQU	0FFFFh
COLOR_BLUE		EQU	043Fh
COLOR_GRAY		EQU	9CD3h

FDC_DMA_BUFFER		EQU	64*2*1024		;64k align * 2 (to leave 128k for kernel size)

?			equ	0

OSM_PTR			EQU	100000h
OSM_MAX_SIZE		EQU	300000h ;x*y*2 (max vga res = 1024 * 768 * 32 bit)
MEM_MGR_MAP		EQU	400000h
MEM_MGR_TABLE		EQU	500000h
PAGE_DIR		EQU	502000h
PAGE_TABLE		EQU	503000h
PAGE_TABLE_SIZE		EQU	400000h


FUNCTION_ARRAY_MAX_ENTRIES	EQU	256
FUNCTION_ARRAY_STRUCT_SIZE	equ	32
;Function_Array_Size		equ	128 * Function_Array_StructSize		;1000h	128 records * 32 bytes = 4096 bytes

DEVICE_ARRAY_STRUCT_SIZE		EQU	10
DEVICE_ARRAY_MAX_ENTRIES		EQU	32
DEVICE_ARRAY_SIZE		EQU	DEVICE_ARRAY_MAX_ENTRIES * DEVICE_ARRAY_STRUCT_SIZE	;max 255 devices

DEVICE_CPU		EQU	1
DEVICE_RAM		EQU	2
DEVICE_VGA		EQU	3
DEVICE_KEYBOARD		EQU	4
DEVICE_MOUSE		EQU	5
DEVICE_IDE		EQU	6
DEVICE_FLOPPY		EQU	7
DEVICE_NETWORK		EQU	8
DEVICE_USB		EQU	9
DEVICE_SOUND		EQU	10
DEVICE_SERIALPORT	EQU	11
DEVICE_PARALERPORT	EQU	12
DEVICE_MODEM		EQU	13
DEVICE_PCMCIA		EQU	14


SCREEN_MEM	equ	0B8000h

MediaInfoSize			EQU	60

FS_FIND_FILE			EQU	1
FS_GET_FILE_SIZE		EQU	2
FS_SET_FILE_SIZE		EQU	3
FS_GET_FILE_SECTOR		EQU	4
FS_DIRLIST			EQU	5
FS_GET_FILE_NEXT_SECTOR		EQU	6
FS_CREATE_FILE			EQU	7
FS_DELETE_FILE			EQU	8

IO_READ				EQU	1

DRIVE_NOT_MOUNTED		EQU	-1
FILE_NOT_EXIST			EQU	-2

STORAGE_DEVICE_STRUCT_SIZE	EQU	14
StorageDeviceArraySize		EQU	24 * STORAGE_DEVICE_STRUCT_SIZE

FILE_NAME_SIZE			EQU	512 - 20 	;512-(5*4)
;name
;driver
;FS
;File pointer
;size
;memory address
OPEN_FILE_STRUCT_SIZE		EQU	FILE_NAME_SIZE + 20
MAX_OPEN_FILES			EQU	50
OpenFilesArraySize		EQU	OPEN_FILE_STRUCT_SIZE * MAX_OPEN_FILES

DMA_READ		EQU	44h		; 46 Read from floppy
DMA_WRITE		EQU	48h		; 4A Write to floppy
SECTOR_SIZE		EQU	512
FLOPPY_DELAY		EQU	2*18
